export const CONTENT = {
  HEADING_EVENTS: "События",
  HEADING_TAXES: "Налоговая база",
  HEADING_DATA_SOURCES: "Источник данных",
  HEADING_BANKS: "Банки",
  HEADING_CASHIERS: "Кассы",
  HEADING_MARKETPLACES: "Маркетплейсы",
  HEADING_INCOME: "Операции",
  SIDER_HEADING_EVENTS: "События",
  SIDER_HEADING_TAXES: "Налоговая база",
  SIDER_HEADING_REPORTS: "Отчётность",
  SIDER_HEADING_DOCUMENT: "Документы",
  SIDER_HEADING_PERSONNEL: "Кадры",
  BANK_SBER: "Сбер",
  BANK_VTB: "ВТБ",
  BANK_ALPHA: "Альфа",
  CASHIERS_FIRST: "Первый ОФД",
  MARKETPLACE_WILDBERRIES: "Wildberries",
  BUTTON_DOWNLOAD_KUDIR: "Скачать КУДиР",
  MARKETPLACE_OZON: "Озон",
  BUTTON_ADD_PAYMENT_TEXT: "Добавить уплату",
  BUTTON_ADD_OPERATION: "Добавить операцию",
  BUTTON_ENS_TEXT: "Пополнить ЕНС",
  BUTTON_SIDER_ADD_TEXT: "Добавить",
  BUTTON_SIDER_EDIT_TEXT: "Редактировать",
  BUTTON_ADD_SOURCE_NON: "Добавить источники данных",
  ENS_ANALYSIS_TEXT: "Анализ ЕНС доступен на платном тарифе",
  TEXT_DETAILS: "Подробнее",
  SELECT_ACCOUNT_NUMBER: "Источник данных",
  SELECT_OPERATION_TYPE: "Тип операции",
  SIDER_SETTINGS: "Настройки",
  SIDER_SUPPORT: "Помощь",
  CARD_TAXES_HEADING: "Налог за 9 месяцев",
  CARD_TAXES_DATE: "до 28.10.23",
  CARD_TAXES_PAID: "уже уплатил ",
  CARD_TAXES_BUTTON_PAID: "Оплачено",
  CARD_FIX_PAYMENT: "Фикс. взнос за `23 год",
  CARD_FIX_PAYMENT_DATE: "до 31.12.23",
  CARD_FIX_PAYMENT_PAID: "уже уплатил ",
  CARD_SUPER_PROFITS: "1% с дохода сверх 300\u00A0000\u00A0₽",
  CARD_SUPER_PROFITS_DATE: "до 01.07.24",
  CARD_SUPER_PROFITS_PAID: "уже уплатил ",
  CLIENT_NAME: "ИП Ягодкин И. В.",
  DEFAULT_DATE: "20.09.2023",
  DEFAULT_DATE_STRING: "сентябрь 2023",
  HAND_LOAD_INFO_TOOLTIP:
    "Важно загрузить все операции за квартал. Только в этом случае расчет налога за период может быть корректным.",
  HEADING_HAND_SOURCERS: "Ручная загрузка",
  HEADING_AUTO_SOURCERS: "Автоматическая загрузка",
  NOTIFICATION_MARKUP_SUCCESS: "Тип операции изменен",
  NOTIFICATION_MARKUP_FAILED: "Ошибка изменения типа операции",
  NOTIFICATION_PROCESSING_SUCCESS: "Операция удалена",
  NOTIFICATION_PROCESSING_FAILED:
    "Ошибка удаления операции, попробуйте еще раз",
  TEXT_NON_TAXES:
    "Расчет налогов в сервисе производится на основании анализа операций из различных источников данных. Важно внести все источники и своевременно подгружать информацию из них.",
  OFF_SOURCE: "Отключить источник",
  DELETE_SOURCE: "Удалить",
  CANCEL_INTEGRATION_SOURCE: "Отменить интеграцию",
  OFF_INTEGRATION_SOURCE: "Отключить интеграцию",
  ADD_SOURCE_COMPLETED: "Добавить данные",
  TOOLTIP_ORANGE: "Требуется дополнительное действие",
  TOOLTIP_GREY: "Данные в процессе добавления. Ожидайте завершения",
  TOOLTIP_DATE: "Дата последней операции",
  FILTER_HEADING: "Фильтр",
}
