export const mockTasks = {
  tasks: [
    {
      type: "usn",
      year: 2023,
      task_code: "ZN4",
      title: "Налог УСН за 2023 год",
      description: "Уплата налога по упрощенной системе налогообложения",
      date_begin: "2024-01-01",
      due_date: "2024-04-28",
      due_amount: 34327,
      accrued_amount: 94327,
      paid_amount: 60000,
      report_code: null,
      purpose: "Единый налоговый платеж по сроку 28 апреля 2024 г.",
    },
    {
      type: "income_percentage",
      year: 2023,
      task_code: "ZV%4",
      title: "1% с дохода за 2023 год",
      description: "Уплата страхового взноса с дохода свыше 300 000 ₽",
      date_begin: "2024-01-01",
      due_date: "2024-07-01",
      due_amount: 23667.46,
      accrued_amount: 33667.56,
      paid_amount: 10000.1,
      report_code: null,
      purpose: "Единый налоговый платеж по сроку 1 июля 2024 г.",
    },
    {
      type: "report",
      year: 2024,
      task_code: "ZDP",
      title: "Декларация УСН за 2023 год",
      description:
        "Сдача налоговой декларации по упрощенной системе налогообложения",
      date_begin: "2024-01-01",
      due_date: "2024-04-25",
      due_amount: null,
      accrued_amount: null,
      paid_amount: null,
      report_code: null,
      purpose: null,
    },
    {
      type: "report",
      year: 2023,
      task_code: "UV3",
      title: "Уведомление по УСН за III кв 2023 года ",
      description:
        "Сдача уведомления об исчисленных авансовых платежах по налогу",
      date_begin: "2023-10-01",
      due_date: "2023-10-25",
      due_amount: null,
      accrued_amount: -12508,
      paid_amount: null,
      report_code: null,
      purpose: null,
    },
    {
      type: "report",
      year: 2023,
      task_code: "UV2",
      title: "Уведомление по УСН за II кв 2023 года ",
      description:
        "Сдача уведомления об исчисленных авансовых платежах по налогу",
      date_begin: "2023-07-01",
      due_date: "2023-07-25",
      accrued_amount: 77017,
    },
    {
      type: "report",
      year: 2023,
      task_code: "UV1",
      title: "Уведомление по УСН за I кв 2023 года ",
      description:
        "Сдача уведомления об исчисленных авансовых платежах по налогу",
      date_begin: "2023-04-01",
      due_date: "2023-04-25",
      due_amount: null,
      accrued_amount: 1409,
      paid_amount: null,
      report_code: "00024",
      report_date: "2023-07-25",
    },
    {
      type: "fixed_fees",
      year: 2023,
      task_code: "SV",
      title: "Фиксированные взносы за 2023 год",
      description:
        "Уплата страхового взноса за ИП в совокупном фиксированном размере",
      date_begin: "2023-01-01",
      due_date: "2024-01-09",
      due_amount: 40000,
      accrued_amount: 45842,
      paid_amount: 5842,
      purpose: "Единый налоговый платеж по сроку 9 января 2024 г.",
    },
    {
      type: "fixed_fees",
      year: 2024,
      task_code: "SV",
      title: "Фиксированные взносы за 2024 год",
      description:
        "Уплата страхового взноса за ИП в совокупном фиксированном размере",
      date_begin: "2024-01-01",
      due_date: "2025-01-08",
      due_amount: 49500,
      accrued_amount: 49500,
      paid_amount: 0,
      purpose: "Единый налоговый платеж по сроку 8 января 2025 г.",
    },
  ],
}
