export const CONTENT = {
  HEADING_TAXES: "Налоги",
  HEADING_DATA_SOURCES: "Источники данных",
  HEADING_BANKS: "Банки",
  HEADING_CASHIERS: "Кассы",
  HEADING_MARKETPLACES: "Маркетплейсы",
  HEADING_INCOME: "Доходы",
  SIDER_HEADING_TAXES: "Налоги",
  SIDER_HEADING_REPORTS: "Отчётность",
  SIDER_HEADING_DOCUMENT: "Документы",
  SIDER_HEADING_PERSONNEL: "Кадры",
  BANK_SBER: "Сбер",
  BANK_VTB: "ВТБ",
  BANK_ALPHA: "Альфа",
  CASHIERS_FIRST: "Первый ОФД",
  MARKETPLACE_WILDBERRIES: "Wildberries",
  MARKETPLACE_OZON: "Озон",
  BUTTON_ADD_PAYMENT_TEXT: "Добавить уплату",
  BUTTON_ENS_TEXT: "Пополнить ЕНС",
  TEXT_DETAILS: "Подробнее",
  SELECT_ACCOUNT_NUMBER: "Номер счета",
  SELECT_OPERATION_TYPE: "Тип операции",
}
