export const CONTENT = {
  TITLE_ADD_SOURCE: "Добавить данные",
  TITLE_BANK_STATEMENT: "Выписка из банка",
  DESCRIPTION_BANK_STATEMENT: "Загрузить выписку в формате 1С (.txt)",
  TITLE_BANK_INTEGRATION: "Интеграция с банком",
  DESCRIPTION_BANK_INTEGRATION: "Альфа-Банк, Модульбанк, Тинькофф, Точка",
  TITLE_ONLINE_CASHIER: "Онлайн-касса",
  DESCRIPTION_ONLINE_CASHIER:
    "ОФД.ру, Первый ОФД, Платформа, СБИС, Контур и т.д.",
  TITLE_MARKETPLACE_INTEGRATION: "Интерграция с маркетплейсом",
  DESCRIPTION_MARKETPLACE_INTEGRATION: "Ozon, Wildberries, Яндекс Маркет",
  NOTIFICATION_PROCESSING_SUCCESS: "Данные сохранены",
  NOTIFICATION_PROCESSING_FAILED: "Не удалось сохранить. Попробуйте еще раз",
  TEXT_UPLOAD_BANK_STATEMENT:
    "Подгрузите выписку в формате .txt (1С), сформированную в ЛК банка. Файл должен содержать все входящие и исходящие операции по одному счету ИП",
  TEXT_UPLOAD_TITLE: "Выберите или перетащите файлы",
  TEXT_LOADING_TITLE: "Загрузка..",
  TEXT_ERROR_TITLE: "Не удалось загрузить данные",
  TEXT_LOADED_TITLE: "Документ загружен",
  TEXT_LOADED_DESCRIPTION:
    "После успешной обработки данные отобразятся в разделе Операции",
  TEXT_UPLOAD_DESCRIPTION: "Загрузите файл в формате .txt",
  BUTTON_BACK: "Назад",
  TEXT_UPLOAD_BANK_INTEGRATION: "Выберите банк",
  TEXT_UPLOAD_ONLINE_CASHIER: "Выберите оператора фискальных данных",
  TEXT_UPLOAD_MARKETPLACE_INTEGRATION: "Выберите маркетплейс",
  BANK_ALPHA: "Альфа-Банк",
  BANK_TINKOFF: "Тинькофф",
  BANK_MODUL: "Модульбанк",
  BANK_TOCHKA: "Точка",
  CASHIER_OFD: "OFD.ru",
  CASHIER_FIRST: "Первый ОФД",
  CASHIER_PLATFORM: "Платформа",
  CASHIER_YANDEX: "Яндекс ОФД",
  CASHIES_SBIS: "СБИС ОФД",
  CASHIER_TAXCOM: "Такском ОФД",
  CASHIER_KONTUR: "Контур",
  CASHIER_OTHER: "Другая касса",
  MARKETPLACE_OZON: "Ozon",
  MARKETPLACE_WB: "Wildberries",
  MARKETPLACE_YANDEX: "Яндекс.Маркет",
  MARKETPLACE_OTHER: "Другой маркетплейс",
  DATA_ACCOUNT: "Номер счета: ",
  DATA_BANKNAME: "Наименование банка: ",
  DATA_STATEMENT_BEGIN: "Дата начала выписки: ",
  DATA_STATEMENT_END: "Дата окончания выписки: ",
}
